### ISSUE TITLE
It takes long time to train DiffPool 

### ISSUE THREAD

**Issue by LucasSlovenia** [diningphil/gnn-comparison#10]
Hi Federico,

I was wondering if it is normal that the training process of DiffPool runs very slowly in your framework? It takes me almost 4h to run 200 epochs for DiffPool on DD dataset with "--debug" on cuda (K80). 

BTW, the training speed for other models in your framework seems fair and acceptable when they run on my machine.

**Comment by diningphil** [comment]
Hi Lucas,

We experienced slow training times for DiffPool and ECC. This is mainly due to the fact that DiffPool operates with dense intermediate adjacency matrices whereas ECC applies an MLP to each edge. Notice that DD, COLLAB and REDDIT-MULTI-5K are the most problematic datasets due to the largest average number of edges per graph.

Perhaps you will find more efficient implementations out there, but that was what we did at the time :)

If you manage to speed up the computation, please let us know!
