### ISSUE TITLE
PyTorch -- multiple threads for each process

### ISSUE THREAD

**Issue by ersisimou** [diningphil/gnn-comparison#17]
Hi,

Many thanks for this framework. 

I would like to ask why you recommend editing the .bashrc in order to not allow PyTorch to spawn multiple threads. Without having done so, it doesn't seem like I encounter any issues. Could you please explain?

Thanks in advance for the response.

**Comment by diningphil** [comment]
Hi,

Thanks for the legit question. When we started to work on this we noticed that each experiment run in parallel tended to use as much threads as possible, therefore creating a bottleneck effect. Perhaps there was a problem with our machine. Honestly, since then we did not check further and blocked Pytorch from spawning multiple threads.

Could you please provide us with the Pytorch version you are using? Is it the same as the one of the installation script?
Thanks!

**Comment by ersisimou** [comment]
Hi,

I am using Pytorch version 1.7.1 (not 1.4.0 as in your installation script) and there is no such problem.

Thanks!
